name: City Creek Creative
favicon: null
layout_spectrum: 0.34854
typography_spectrum: 0.2383182558696717
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6b8a8c'
    - '#050e15'
    - '#dbbf80'
    - '#5ec4b6'
  brandStrength: 0.8356193639338017
  lightness: 0.3125
  saturation: 0.6545794589910656
  rhythmicContrast: 0.06846060091629624
purpose: []
